version: '3.8'

services:
  proxysql:
    image: proxysql/proxysql:2.6.0
    container_name: proxysql
    ports:
      - "6032:6032"   # Admin port
      - "6033:6033"   # MySQL port
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf    
      - ./proxysql-data:/var/lib/proxysql    
    restart: always

  mariadb-master:
    image: mariadb:10.6
    container_name: mariadb-master
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3311:3306"
    volumes:
      - ./master:/docker-entrypoint-initdb.d
      - ./master-data:/var/lib/mysql
    command: >
      --server-id=1
      --log-bin=mariadb-bin
      --binlog-format=row
      --gtid-domain-id=1
      --log-slave-updates=ON
      --skip-bind-address
      --skip-name-resolve

  mariadb-slave-1:
    image: mariadb:10.6
    container_name: mariadb-slave-1
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3312:3306"
    depends_on:
      - mariadb-master
    volumes:
      - ./slave:/docker-entrypoint-initdb.d
      - ./mariadb-slave-1-data:/var/lib/mysql
    command: >
      --server-id=2
      --relay-log=relay-log
      --log-bin=mariadb-bin
      --read-only=ON
      --gtid-domain-id=1
      --skip-bind-address
      --skip-name-resolve

  mariadb-state-ch-master:
    image: mariadb:10.6
    container_name: mariadb-state-ch-master
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3321:3306"
    volumes:
      - ./master:/docker-entrypoint-initdb.d
      - ./mariadb-state-ch-master-data:/var/lib/mysql
    command: >
      --server-id=3
      --log-bin=mariadb-bin
      --binlog-format=row
      --gtid-domain-id=1
      --log-slave-updates=ON
      --skip-bind-address
      --skip-name-resolve

  mariadb-state-ch-slave-1:
      image: mariadb:10.6
      container_name: mariadb-state-ch-slave-1
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3322:3306"
      depends_on:
        - mariadb-state-ch-master
      volumes:
        - ./slave:/docker-entrypoint-initdb.d
        - ./mariadb-state-ch-slave-1-data:/var/lib/mysql
      command: >
        --server-id=4
        --relay-log=relay-log
        --log-bin=mariadb-bin
        --read-only=ON
        --gtid-domain-id=1
        --skip-bind-address
        --skip-name-resolve
  

