version: '3.8'

services:
  proxysql:
    image: proxysql/proxysql:2.6.0
    container_name: proxysql
    ports:
      - "6032:6032"   # Admin port
      - "6033:6033"   # MySQL port
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf     # Optional custom config
      - proxysql_data:/var/lib/proxysql
    restart: always

  mysql-master:
    container_name: mysql-master
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./master:/docker-entrypoint-initdb.d
      - mysql_master_data:/var/lib/mysql
    command:
      --server-id=1
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --log-bin=mysql-bin
      --default-authentication-plugin=mysql_native_password
      --log-slave-updates=ON
      # --binlog-do-db=testdb

  mysql-replica1:
    container_name: mysql-replica1
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql-master
    volumes:
      - ./replica1:/docker-entrypoint-initdb.d
      - mysql_replica1_data:/var/lib/mysql
    command:
      --server-id=2
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --relay-log=relay-bin
      --read-only=ON
      --default-authentication-plugin=mysql_native_password
      --log-slave-updates=ON

  mysql-replica2:
    container_name: mysql-replica2
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql-master
    volumes:
      - ./replica2:/docker-entrypoint-initdb.d
      - mysql_replica2_data:/var/lib/mysql
    command:
      --server-id=3
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --relay-log=relay-bin
      --read-only=ON
      --default-authentication-plugin=mysql_native_password
      --log-slave-updates=ON
  
  volumes:
    proxysql_data:
    mysql_master_data:
    mysql_replica1_data:
    mysql_replica2_data:
